openapi: 3.1.0
info:
  title: SeoTesterOnline API
  description: Analizza siti web per metriche SEO con SeoTesterOnline.
  version: 1.0.0

servers:
  - url: https://api.seotesteronline.com
    description: Server principale di SeoTesterOnline

paths:
  /analyze:
    get:
      operationId: analyzeSeo
      summary: Analizza un sito per metriche SEO
      parameters:
        - name: url
          in: query
          required: true
          description: L'URL del sito da analizzare
          schema:
            type: string
      responses:
        '200':
          description: Risultato dell'analisi SEO
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
